### ISSUE TITLE
Allow dev-dependencies in __test-helpers__ directory

### ISSUE THREAD

**Issue by mattii** [picter/eslint-config-picter#4]
Currently there's an `import/no-extraneous-dependencies` error if you import dev-dependencies into modules inside `src/__test-helpers__`. Would be nice to allow dev imports in this directory, too.

If it is applied, we can remove this eslint-flag: https://git.picter.com/picter/app-artists/commit/d5477397aac36296024cbd358eedfc08be3ce7a8

**Comment by noxan** [comment]
Isn't there a way to configure global excludes for exactly this use case? Or did I use it with `tslint`?

**Comment by mattii** [comment]
You mean global excludes for all eslint-rules? That's not what I mean.

We only need to add the directory `src/__test-helpers/**/*` (not tested!) here: https://github.com/picter/eslint-config-picter/blob/master/index.js#L13

**Comment by noxan** [comment]
Sounds good :)

Maybe just exclude the '__test-helpers__' folder in general. Otherwise we will get problems with nested ones sooner or later.

**Comment by mattii** [comment]
The same exception should be added for `.stories.jsx` files.
